### ISSUE TITLE
pre_training

### ISSUE THREAD

**Issue by Justarrrrr** [YtongXie/MedIM#1]
hi, i've read your paper, and i'm trying to implement your model. But i meet some problems.
I would like to ask why there is no file MeSH_preprocess.py in the code directory data/meta, and what is the purpose of this file

**Comment by YtongXie** [comment]
Thanks for your question. In fact, the MeSH_preprocess.py is useless. We have revised README.md.

**Comment by Justarrrrr** [comment]
thank u for your reply 
but why when i run the MeSH_pickle_train.py, i meet the error:
![image](https://github.com/user-attachments/assets/53908ce4-967e-47d6-bfad-8dfbcb9cac0b)
![image](https://github.com/user-attachments/assets/a2dcfcfa-5e30-4920-9b74-f1c58c9c0387)
![image](https://github.com/user-attachments/assets/62741c43-51cd-47c4-8ca6-021a817d85e6)

**Comment by YtongXie** [comment]
Could you please check if the MIMIC data is located in the correct directory?

**Comment by Justarrrrr** [comment]
yeah, is it correct?
![image](https://github.com/user-attachments/assets/d7343c7b-ad2b-4a49-bd32-f447691e9d30)

**Comment by YtongXie** [comment]
![1729054722441](https://github.com/user-attachments/assets/2d41624a-7cbe-4cee-aa55-8c89cf01a031)
Please follow this format. Put the images and reports into the same folder.

**Comment by Justarrrrr** [comment]
do u mean that the corresponding image is in the folder s51613820

**Comment by Justarrrrr** [comment]
this is my image dir
![image](https://github.com/user-attachments/assets/f0a78f5c-eb3b-4d46-b158-5595303b63f8)
and this is my corresponding report dir
![image](https://github.com/user-attachments/assets/f4d88b44-3e8a-40fd-af33-02ce357c3c38)
is this ok?

**Comment by YtongXie** [comment]
![1729058854246](https://github.com/user-attachments/assets/d2c83aed-7f46-4b13-9d1d-58fd22777ad4)
Yes, the corresponding image is in the folder s51613820

**Comment by Justarrrrr** [comment]
thank u for your reply, i've solved this error.
That's because i add a '/' below , i've delete it
![image](https://github.com/user-attachments/assets/d1cf76ab-c27f-4ae5-a75c-cc984de54bec)
thank you!
